### ISSUE TITLE
Helpfiles

### ISSUE THREAD

**Issue by paul-vdb** [javalake2023/uc511#5]
@javalake2023 The BAS function still uses the data(Fed_MPAs_clipped) example but it has been removed from this package.
Are we planning on having worked examples? I see that you reference North Carolina data from the sf pacakage via `sf::st_read(system.file("shape/nc.shp", package="sf"))`

Can that example go both into the HaltonFrame and BAS helpfiles?

**Comment by javalake2023** [comment]
Examples using the sf NC shapefile have been added to all user-facing functions.
